// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * 
 */
public class Mummy extends Monster {
};

//----------------------- METHODS ---------------------------//

	/**
	 * Class constructor for the Spider monster type
	 */
public class Mummy extends Monster {
	public Mummy() {
		this.name='Mummy';
		this.health=0.44;
		this.performance=1.222;
		this.isDead=false;
		this.type='Monster';
	}
}
/**
* performAction implementation over a single victim
* @param victim: Individual instance over which we want to
* perform the action. The attack can only be performed every 2 turns
*/
public abstract void performAction(Individual victim) {
	victim.health -= this.performance;
}