// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * 
 */
public class Slime extends Monster {
};
//----------------------- METHODS ---------------------------//

	/**
	 * Class constructor for the Spider monster type
	 */
public class Slime extends Monster {
	public Slime() {
		this.name='Slime';
		this.health=0.44;
		this.performance=1.222;
		this.isDead=false;
		this.type='Monster';
	}
}
/**
* performAction implementation over a single victim
* @param victim: Individual instance over which we want to
* perform the action. I this case the attack is followed by
* the attacked character losing the next turn.
*/
public abstract void performAction(Individual victim) {
	victim.health -= this.performance;
}